requires 'SignalWire::RestAPI', '1.7';
requires 'SignalWire::ML', '1.20';
requires 'LWP::Protocol::https', '6.10';
requires 'Plack', '1.0050';
requires 'Plack::App::WebSocket', '0.08';
requires 'Twiggy', '0.1026';
requires 'Data::Dumper', '2.174';
requires 'LWP::UserAgent', '6.70';
requires 'JSON::PP', '4.16';
requires 'URI::Encode', 'v1.1.1';
requires 'HTTP::Request::Common', '6.44';
requires 'HTML::Template::Expr', '0.07';
requires 'DateTime', '1.59';



