INSERT INTO roomie_menu (roomie_company_id, name, description, sku, price, category) VALUES
(1, 'French Toast', 'Classic French Toast served with maple syrup and fresh berries.', 'CFT001', 15, 'Breakfast'),
(1, 'Avocado Toast', 'Multigrain bread topped with smashed avocado, poached egg, and a sprinkle of chili flakes.', 'AVT002', 12, 'Breakfast'),
(1, 'Eggs Benedict', 'Poached eggs on an English muffin with ham and hollandaise sauce.', 'EGB003', 16, 'Breakfast'),
(1, 'Caesar Salad', 'Crisp romaine lettuce, Parmesan cheese, croutons, and a creamy Caesar dressing.', 'CSR004', 10, 'Lunch'),
(1, 'Grilled Chicken Caesar', 'Caesar Salad topped with grilled chicken.', 'CSG005', 14, 'Lunch'),
(1, 'Shrimp Caesar Salad', 'Caesar Salad topped with shrimp.', 'CSS006', 16, 'Lunch'),
(1, 'Quinoa Bowl', 'Quinoa & Roasted Vegetable Bowl mixed with a light lemon vinaigrette.', 'QRB007', 13, 'Lunch'),
(1, 'Club Sandwich', 'Classic triple-layered sandwich with turkey, bacon, lettuce, tomato, and mayonnaise, served with fries.', 'CLB008', 14, 'Lunch'),
(1, 'Grilled Salmon', 'Grilled Salmon with a dill sauce, served alongside asparagus and quinoa.', 'GSM009', 25, 'Dinner'),
(1, 'Ribeye Steak', '8 oz. steak served with mashed potatoes and seasonal vegetables.', 'RBS010', 30, 'Dinner'),
(1, 'Pasta Primavera', 'Sautéed seasonal vegetables tossed with pasta in a light garlic and olive oil sauce.', 'PSP011', 18, 'Dinner'),
(1, 'Coffee', 'Freshly brewed, available in decaf or regular.', 'COF012', 4, 'Beverage'),
(1, 'Herbal Tea', 'A soothing selection of herbal teas.', 'TEH013', 3, 'Beverage'),
(1, 'Green Tea', 'Refreshing and aromatic green tea.', 'TEG014', 3, 'Beverage'),
(1, 'Black Tea', 'Robust and full-bodied black tea.', 'TEB015', 3, 'Beverage'),
(1, 'Coke', 'A classic favorite cola.', 'COK016', 2, 'Beverage'),
(1, 'Pepsi', 'A sweeter alternative cola.', 'PEP017', 2, 'Beverage'),
(1, 'Dr. Pepper', 'A unique blend of 23 flavors for an unmistakable taste.', 'DRP018', 2, 'Beverage'),
(1, 'Ribeye Steak Rare', 'Ribeye Steak cooked to a rare temperature.', 'RBR019', 30, 'Dinner'),
(1, 'Ribeye Steak Medium Rare', 'Ribeye Steak cooked to a medium rare temperature.', 'RBM020', 30, 'Dinner'),
(1, 'Ribeye Steak Medium', 'Ribeye Steak cooked to a medium temperature.', 'RBM021', 30, 'Dinner'),
(1, 'Ribeye Steak Medium Well', 'Ribeye Steak cooked to a medium well temperature.', 'RBW022', 30, 'Dinner'),
(1, 'Ribeye Steak Well Done', 'Ribeye Steak cooked to a well done temperature.', 'RBW023', 30, 'Dinner');
